namespace WatchShop_Core.Domain.Enums
{
    public enum AdditionalCharacteristicsEnum
    {
        Bluetooth = 1,
        GPS = 2,
        NFC = 3,
        AutomaticCalendar = 4,
        Accelerometer = 5,
        AntiGlare,
        Barometer,
        LargeDate,
        AlarmClock,
        VibratingAlarm,
        MilitaryTime,
        MusicPlaybackAndControl,
        RotatingBezel,
        SecondTime,
        Altimeter,
        Gyroscope,
        DepthMeter,
        TidalGraph,
        BloodOxygenSaturationSensor,
        Designer,
        Notebook,
        FamousModel,
        PowerReserveIndicator,
        ChargeIndicator,
        DateIndication,
        DayOfWeekIndication,
        MonthIndication,
        FishermansCalendar,
        Calculator,
        Compass,
        LunarCalendar,
        MagneticResistance,
        SleepMonitoring,
        FrostResistance,
        AwardWinningModel,
        CallSupport,
        Backlight,
        CalorieCounting,
        SemiSkeleton,
        PromotionalModel,
        Shockproof,
        HeartRateMonitor,
        RadioControl,
        Regulator,
        Stopwatch,
        TouchScreen,
        Skeleton,
        iOSCompatibility,
        AndroidCompatibility,
        SolarBattery,
        Timer,
        TactileGlass,
        TacticalWatches,
        Tachymeter,
        Telemeter,
        Thermometer,
        Tourbillon,
        PhoneFinder,
        Chronograph,
        Chronometer,
        Pedometer
    }
}
